#!/bin/bash
#SBATCH -J SL5
#SBATCH -N 10
#SBATCH -n 360
#SBATCH --ntasks-per-node=36
#SBATCH --ntasks-per-core=10
#SBATCH --mail-type=ALL

module purge
module load intel/18.2 intelmpi/18.2
module list

srun pw.x -ndiag 144 < scf_NSi_512off.in >  scf_NSi_512off.out

wait
